import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { cx } from "class-variance-authority"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cx(inter.className, "flex flex-col h-screen w-screen overflow-hidden")}>{children}</body>
    </html>
  )
}
